---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: gitlab-project
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../files/projectrequests/gitlab"
- object: deployments
  content:
  - name: gitlab
    namespace: gitlab
    template: "{{ inventory_dir }}/../files/templates/gitlab-ssl.yml"
    params: "{{ inventory_dir }}/../files/params/gitlab-params"
